source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'i18n', '>=0.6.5'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails'
gem 'minitest-rails'
gem 'minitest-rails-capybara'
gem 'pg'
gem 'rails', '4.0.0.rc2'
gem 'sass-rails', '~> 4.0.0.rc2'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
